version: "3"

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    container_name: rabbitmq-masterdev
    ports:
      - 5672:5672
      - 15672:15672

networks:
  postgres-network:
    driver: bridge